services:
  - type: web
    name: eduswapper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "src.main:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
    plan: free
